/// <reference path="../Scripts/typings/jquery/jquery.d.ts" />

// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

module AutoGeneratedCode {

    export interface Movie {
        Title: string;
        Plot: string;
        Rating: string;
        Screenings: string[];
        background_image: string;
    }

}

class AppHandler {
    _movies: AutoGeneratedCode.Movie[];

    constructor(moviesJson: any) {
        this._movies = <AutoGeneratedCode.Movie[]>moviesJson;


    }

    public GetMovie(elementAt: number): AutoGeneratedCode.Movie {
        var movie = this._movies[elementAt];
        return movie;

    }


    public GetAllMovies(): AutoGeneratedCode.Movie[] {

        var movies = this._movies;
        return movies;
    }

}
